name: mmaster_environment
channels:
  - conda-forge
dependencies:
  - cmake
  - gcc
  - gxx
  - qt
  - exiv2
  - exiftool
  - mesa-libgl-devel-cos7-x86_64
  - fiona
  - gdal
  - geopandas
  - h5py
  - matplotlib
  - pandas
  - pyproj
  - pybob
  - scikit-image
  - scipy
  - shapely
